### PR TITLE
minor updates: plotting functions, exp correction

### PR DESCRIPTION
**Pull request by n-leo**
- functions to plot the stream files
- exponential correction of dwell time with growth height

### CODE REVIEW

**Comment by n-leo** [comment]
Alternatively to the proposed code changes, the examples could be updated -- apparently the exponential correction and the plot functions were not available in ipython notebooks.
image
image

**Comment by Skoricius** [comment]
Thanks @n-leo! Before I review the PR, can you make sure it passes all the automatic tests. I.e. you need to run formatting by doing `black f3ast` and `isort f3ast`. That's going to fix formatting inconsistencies and reduce the diff with the current code.

**Comment by Skoricius** [comment]
Inactive for 3 months. I've added the essentials bits of this in the main code and closing now.

**Comment by Skoricius** [comment]
Inactive for 3 months. I've added the essentials bits of this in the main code and closing now.

**Pull request closed without merging**
